### ISSUE TITLE
egg-amqplib 在rabbitmq服务重启后无法自动连接？

### ISSUE THREAD

**Issue by meguoe** [zubinzhang/egg-amqplib#11]
egg-amqplib 在rabbitmq服务重启后无法自动连接？

你好，我在使用egg-amqplib过程中发现，如果因为网络或者其他原因导致mq连接断开，在网络或MQ服务恢复正常后egg-amqplib还是发送消息失败，我判断是因为没有重新连接，使用的还是旧连接发送消息，所以导致失败。不知道您是否清楚此情况？

**Comment by zubinzhang** [comment]
试了下应该是断线之后没有重新连接，记得`amqplib` 这个包貌似是没有断线自动重连的, 需要另外处理一下
